platform:ios,'7.0'

target "TimeAccumulation" do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh', '~>3.0.0'
pod 'CustomIOSAlertView', '~> 0.9.3'
pod 'FMDB', '~> 2.6.2'

end